# raise ValueError('Error!!!')

# class MyException(Exception):
#     pass

# raise MyException('Error!')


# a = 1
# b = 0
# try:
#     print(a / b)
# except:
#     b = 10
#     print(a / b)    
# print('ok')

# try:
#     num = int(input('Enter num: '))
#     print(num / 0)
# except ValueError:
#     print('Please enter number!')
# except ZeroDivisionError:
#     print('Tra again!')